import { TInput } from "@/types";

export const createUserInput: TInput[] = [
  {
    id: "name_item",
    label: "Nombre",
    labelClass: "label",
    type: "text",
    placeholder: "Ej: Juan Perez",
    name: "name",
    editable: true,
    containerClass: "sm:col-span-3",
    inputClass: "input",
  },
  {
    id: "username_item",
    label: "Nombre de Usuario",
    labelClass: "label",
    type: "text",
    placeholder: "Ej: Juanito",
    name: "username",
    editable: true,
    containerClass: "sm:col-span-3",
    inputClass: "input",
  },
  {
    id: "email_item",
    label: "Correo",
    labelClass: "label",
    type: "email",
    placeholder: "Ej: 9sRFP@example.com",
    name: "email",
    editable: true,
    containerClass: "sm:col-span-4",
    inputClass: "input",
  },
  {
    id: "password_item",
    label: "Contraseña",
    labelClass: "label",
    type: "password",
    placeholder: "Ej: ********",
    name: "password",
    editable: true,
    containerClass: "sm:col-span-3",
    inputClass: "input",
  },
  {
    id: "confirm_password_item",
    label: "Confirmar Contraseña",
    labelClass: "label",
    type: "password",
    placeholder: "Ej: ********",
    name: "confirmPassword",
    editable: true,
    containerClass: "sm:col-span-3",
    inputClass: "input",
  },
  {
    id: "address_item",
    label: "Dirección",
    labelClass: "label",
    type: "text",
    placeholder: "Ej: Calle 123",
    name: "address",
    editable: true,
    containerClass: "sm:col-span-full",
    inputClass: "input",
  },
  {
    id: "municipality_item",
    label: "Municipio",
    labelClass: "label",
    type: "text",
    placeholder: "Ej: San Jose",
    name: "municipality",
    editable: true,
    containerClass: "sm:col-span-2 sm:col-start-1",
    inputClass: "input",
  },
  {
    id: "CI_item",
    label: "C.I",
    labelClass: "label",
    type: "text",
    placeholder: "Ej: 123456789",
    name: "CI",
    editable: true,
    containerClass: "sm:col-span-2",
    inputClass: "input",
  },
  {
    id: "phone_item",
    label: "Telefono",
    labelClass: "label",
    type: "text",
    placeholder: "Ej: 123456789",
    name: "phone",
    editable: true,
    containerClass: "sm:col-span-2",
    inputClass: "input",
  },
];
